---
title: "analysis"
output: pdf_document
date: "2022-12-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
master_df = read.csv('master_df.csv')
set.seed(156)

OS_est = function(z, y, x, out.family = gaussian, 
                  truncpscore = c(0, 1))
{
     ## fitted propensity score
     pscore   = glm(z ~ x, family = binomial)$fitted.values
     pscore   = pmax(truncpscore[1], pmin(truncpscore[2], pscore))
     
     ## fitted potential outcomes
     outcome1 = glm(y ~ x, weights = z, 
                    family = out.family)$fitted.values
     outcome0 = glm(y ~ x, weights = (1 - z), 
                    family = out.family)$fitted.values
     
     ## regression imputation estimator
     ace.reg  = mean(outcome1 - outcome0) 
     ## IPW estimators
     ace.ipw0 = mean(z*y/pscore - (1 - z)*y/(1 - pscore))
     ace.ipw  = mean(z*y/pscore)/mean(z/pscore) - 
                   mean((1 - z)*y/(1 - pscore))/mean((1 - z)/(1 - pscore))
     ## doubly robust estimator
     res1     = y - outcome1
     res0     = y - outcome0
     ace.dr   = ace.reg + mean(z*res1/pscore - (1 - z)*res0/(1 - pscore))

     return(c(ace.reg, ace.ipw0, ace.ipw, ace.dr))     
}


OS_ATE = function(z, y, x, n.boot = 2*10^2,
                     out.family = gaussian, truncpscore = c(0, 1))
{
     point.est  = OS_est(z, y, x, out.family, truncpscore)
     
     ## nonparametric bootstrap
     n.sample   = length(z)
     x          = as.matrix(x)
     boot.est   = replicate(n.boot, 
                  {id.boot = sample(1:n.sample, n.sample, replace = TRUE)
                  OS_est(z[id.boot], y[id.boot], x[id.boot, ], 
                         out.family, truncpscore)})

     boot.se    = apply(boot.est, 1, sd)
     
     res        = rbind(point.est, boot.se)
     rownames(res) = c("est", "se")
     colnames(res) = c("reg", "HT", "Hajek", "DR")
     
     return(res)
}


Z = as.integer((master_df$GDP_G_L) < 0)
Y = master_df$ANY_PRIO
X = as.matrix(master_df[, c(c(85,61,51,56,49,36), 100:179)])

pscore = glm(Z ~ X, family = binomial)$fitted.values
hist(pscore)
hist(pscore[Z==1])
hist(pscore[Z==0])

causaleffects = OS_ATE(Z, Y, X, 
                      out.family = binomial, n.boot = 1000, truncpscore = c(0.1,0.9))
round(causaleffects, 3)
rbind(causaleffects[1, ] - 1.96*causaleffects[2, ],
      causaleffects[1, ] + 1.96*causaleffects[2, ])

```

