---
title: "Replication of Miguel 2004 Civil Conflict and Economic Shock"
author: "Sam Tan"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, results='hide',message=FALSE, warning=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(skimr)
library(AER) # AER::ivreg()
library(fastDummies) # dummycols()
library(sandwich) 
library(stargazer)
knitr::opts_knit$set(root.dir = "/Users/samtan/Downloads/Replication of Miguel's study")
```

## Civil Conflict


```{r}
main =readxl::read_excel("ucdp-prio-acd-3-2005.xls")
africa = read_csv('cow_code.csv')
# raw = haven::read_dta('dataverse_files-4/mss_repdata.dta')
```


```{r}
#main %>%  mutate(COW_location = as.numeric(COW_location)) %>% select(Startdate) %>% skimr::skim()


monadic = main %>% 
  select(Type, Intensity, YEAR, COW_location, Location) %>%
  pivot_wider(id_cols = c(YEAR,COW_location), names_from = Type,values_from = Intensity, values_fn = max, names_prefix = 'Type', values_fill = 0) 



monadic_africa_conflict = monadic %>% 
  filter(COW_location %in% africa$CCode) %>% 
  mutate(COW_location = as.numeric(COW_location))
  
monadic_africa_empty = map_df(1:nrow(africa), function(i){
  # For Namibia, only 9 years are observed (1990 - 1999), instead of all years. Source: Armed Conflict Dataset Codebook, Version 3-2005, page 24
  if (africa$StateNme[i] == 'Namibia') {
    bind_cols(Location = africa$StateNme[i], 
        COW_location = africa$CCode[i], 
        YEAR = 1990:1999)  
  }
  else{
    bind_cols(Location = africa$StateNme[i], 
        COW_location = africa$CCode[i], 
        YEAR = 1980:2000) # include 1980 and 2000 for the onset and offset variable
    }
})


monadic_africa_all = left_join(
  monadic_africa_empty, 
  monadic_africa_conflict, 
  by = c('COW_location','YEAR'))  %>% 
  mutate_if(is.numeric,coalesce,0) %>% # The default is peace. No conflict.
  mutate(WAR_PRIO = ((Type3 == 3)|(Type4 == 3)), 
         WAR_PRIO_ON = ((lag(WAR_PRIO == F, default = F) & (WAR_PRIO == T))),
         WAR_PRIO_OFF = ((lag(WAR_PRIO == T, default = F) & (WAR_PRIO == F))), 
         MINOR_PRIO = ((Type3 == 1)|(Type3 == 2)|(Type4 == 1) | (Type4 == 2)), 
         MINOR_PRIO_ON = ((lag(MINOR_PRIO == F, default = F) & (MINOR_PRIO == T))), 
         MINOR_PRIO_OFF = ((lag(MINOR_PRIO == T, default = F) & (MINOR_PRIO == F))), 
         ANY_PRIO = ((Type3 == 1)|(Type3 == 2)|(Type3 == 3)|(Type4 == 1) | (Type4 == 2) | (Type4 == 3)), 
         ANY_PRIO_ON = (lag(ANY_PRIO == F,default = F) & (ANY_PRIO == T)),
         ANY_PRIO_OFF = ((lag(ANY_PRIO == T, default = F) & (ANY_PRIO == F)))) 

monadic_africa_all$ANY_PRIO_ON[lag(monadic_africa_all$ANY_PRIO)] <- NA
monadic_africa_all$ANY_PRIO_OFF[!lag(monadic_africa_all$ANY_PRIO)] <- NA
monadic_africa_all$MINOR_PRIO_ON[lag(monadic_africa_all$MINOR_PRIO)] <- NA
monadic_africa_all$MINOR_PRIO_OFF[!lag(monadic_africa_all$MINOR_PRIO)] <- NA
monadic_africa_all$WAR_PRIO_ON[lag(monadic_africa_all$WAR_PRIO)] <- NA
monadic_africa_all$WAR_PRIO_OFF[!lag(monadic_africa_all$WAR_PRIO)] <- NA

monadic_africa_all =  monadic_africa_all %>%
    filter((YEAR >= 1981) & (YEAR <= 1999))
```

# Merge data

```{r}
df = read_csv('clean_data.csv')
merged_df = inner_join(x = df, y = monadic_africa_all,by = c('year' = 'YEAR', 'ccode' = 'COW_location'))

# write_csv(x = merged_df, file = 'merged_df.csv')
```

# Data Cleaning 
```{r results='asis'}

# model 1: Economic Growth Rate ~ Growth in rainfall at time t + Growth in rainfall at t - 1. 
m1 = lm(formula = GDP_G ~ GPCP_G + GPCP_G_L, data = merged_df)
m1.se = sqrt(diag(sandwich::vcovCL(m1, cluster = ~ccode,type = 'HC1')))

# model 2: Economic Growth Rate ~ Growth in rainfall, t +  Growth in rainfall, t - 1 + covariates
X = c('Y_0','polity2l','ethfrac','relfrac','Oil','lmtnest','lpopl1')
X_log = c('log_Y_0','polity2l','ethfrac','relfrac','Oil','lmtnest','lpopl1')
# fixed effect for each country (in dummies)
Iccode = fastDummies::dummy_cols(.data = merged_df$ccode,remove_selected_columns = T,remove_first_dummy = T) %>% tibble()

# extract the years for each country in dummies form
Iccyear = Iccode * merged_df$year 

# merge the dummies to the main dataframe
names(Iccode) = paste0("Iccode", names(Iccode))
names(Iccyear) = paste0("Iccyear", names(Iccyear))
Iccyear = Iccyear %>% rowid_to_column("ID")
Iccode = Iccode %>% rowid_to_column("ID")
merged_df = merged_df %>% rowid_to_column("ID")
dummies_df = left_join(x = Iccode, y = Iccyear, by = 'ID')
master_df = left_join(merged_df,dummies_df,by = c('ID' = 'ID'))  

# model formula for m2
m2formula = reformulate(termlabels = c(grep('Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L',X),response = 'GDP_G')
m2 = lm(formula = m2formula, data = master_df)
m2.se = sqrt(diag(sandwich::vcovCL(m2, cluster = ~ccode,type = 'HC1')))

# m3
m3formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'),response = 'GDP_G')

m3 = lm(formula = m3formula, data = master_df)
m3.se = sqrt(diag(sandwich::vcovCL(m3, cluster = ~ccode,type = 'HC1')))

# m4
m4formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L',"GPCP_G_FL"),response = 'GDP_G')

m4 = lm(formula = m4formula, data = master_df)
m4.se = sqrt(diag(sandwich::vcovCL(m4, cluster = ~ccode,type = 'HC1')))


# m5
m5formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L','TOT_100_G'),response = 'GDP_G')

m5 = lm(formula = m5formula, data = master_df)
m5.se = sqrt(diag(sandwich::vcovCL(m5, cluster = ~ccode,type = 'HC1')))

# table 2
stargazer(m1,m2,m3,m4,m5,se=list(m1.se,m2.se,m3.se,m4.se,m5.se),header = F, type = 'text', omit = c('Iccyear','Iccode'), omit.labels = c("Country-speciﬁc time trend","Country fixed effect"),column.label = "Economic Growth Rate, t")
```

# T4: OLS VERSUS 2SLS

```{r}
master_df = master_df %>% mutate(year_actual = year, year = year_actual - 1978)
rformula = reformulate(termlabels = c(X,'GDP_G', 'GDP_G_L', 'year'),response = 'ANY_PRIO')
probit_model = glm(rformula, family = binomial(link = "probit"), data = master_df)
probit.se = sqrt(diag(sandwich::vcovCL(probit_model, cluster = ~ccode,type = 'HC1')))

rformula2 = reformulate(termlabels = c(X,'GDP_G', 'GDP_G_L', 'year'),response = 'ANY_PRIO')
ols2 = lm(rformula2, data = master_df)
ols2.se = sqrt(diag(sandwich::vcovCL(ols2, cluster = ~ccode,type = 'HC1')))


master_df = master_df %>% mutate(log_Y_0 = log(Y_0))
rformula3 = reformulate(termlabels = c(grep('Iccyear',x = names(master_df),value = T),X,'GDP_G', 'GDP_G_L'),response = 'ANY_PRIO')
ols3 = lm(rformula3, data = master_df)
ols3.se = sqrt(diag(sandwich::vcovCL(ols3, cluster = ~ccode,type = 'HC1')))

# OLS 4:
rformula4 = reformulate(termlabels = c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G', 'GDP_G_L'),response = 'ANY_PRIO')
ols4 = lm(rformula4, data = master_df)
ols4.se = sqrt(diag(sandwich::vcovCL(ols4, cluster = ~ccode,type = 'HC1')))

# IV 2SLS 5:
# stage 1:
m5formula1 = reformulate(c(grep('Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L',X))
# stage 2: 
m5formula2 = reformulate(c(grep('Iccyear',x = names(master_df),value = T),X,'GDP_G_L', "GDP_G"),response = 'ANY_PRIO')

iv2sls_5 = ivreg(formula = m5formula2, instruments = m5formula1, data = master_df)
iv2sls_5.se = sqrt(diag(sandwich::vcovCL(iv2sls_5, cluster = ~ccode,type = 'HC1')))
rmse5 = sqrt(mean(iv2sls_5$residuals^2))

# IV 2SLS 6:
# stage 1:
m6formula1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'))
# stage 2: 
m6formula2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G"),response = 'ANY_PRIO')
#m5_2 = lm(m5formula2, data = master_df)

iv2sls_6 = ivreg(formula = m6formula2, instruments = m6formula1, data = master_df)
iv2sls_6.se = sqrt(diag(sandwich::vcovCL(iv2sls_6, cluster = ~ccode,type = 'HC1')))
rmse6 = sqrt(mean(iv2sls_6$residuals^2))

# IV 2SLS 7:
# stage 1:
m7formula1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'))
# stage 2: 
m7formula2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G"),response = 'WAR_PRIO')

iv2sls_7 = ivreg(formula = m7formula2, instruments = m7formula1, data = master_df)
iv2sls_7.se = sqrt(diag(sandwich::vcovCL(iv2sls_7, cluster = ~ccode,type = 'HC1')))
rmse7 = sqrt(mean(iv2sls_7$residuals^2))

# Summary table 4:
stargazer(probit_model,ols2,ols3,ols4,iv2sls_5,iv2sls_6,iv2sls_7,se = list(probit.se, ols2.se, ols3.se, ols4.se, iv2sls_5.se, iv2sls_6.se, iv2sls_7.se), header = F, type = 'text', omit = c('Iccyear','Iccode'), omit.labels = c("Country-speciﬁc time trend","Country fixed effect"))
```

# Table 3
```{r}
master_df = master_df[!is.na(master_df$GDP_G),]
t3_m1formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'),response = 'ANY_PRIO')

t3_m1 = lm(formula = t3_m1formula, data = master_df)
t3_m1.coef = t3_m1$coefficients
t3_m1.se = sqrt(diag(sandwich::vcovCL(t3_m1, cluster = ~ccode,type = 'HC1')))


t3_m2formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'),response = 'WAR_PRIO')

t3_m2 = lm(formula = t3_m2formula, data = master_df)
t3_m2.coef = t3_m2$coefficients
t3_m2.se = sqrt(diag(sandwich::vcovCL(t3_m2, cluster = ~ccode,type = 'HC1')))

stargazer(t3_m1,t3_m2,header = F, type = 'text', omit = c('Iccyear','Iccode'), omit.labels = c("Country-speciﬁc time trend","Country fixed effect"), se = list(t3_m1.se,t3_m2.se)) 
```

# Table 5: Interactions between Economic Growth and Country Characteristics Dependent Variable: Civil Conﬂict ≥25 Deaths

```{r}
# IV 2SLS (1): Interactions between Economic Growth and Democracy on Civil Conﬂict

## stage 1:
t5_f1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L', "polity2l*GPCP_G", "polity2l*GPCP_G_L"))
## stage 2: 
t5_f2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G", "polity2l*GDP_G_L", "polity2l*GDP_G"),response = 'ANY_PRIO')

iv2sls_1 = ivreg(formula = t5_f1, instruments = t5_f2, data = master_df)
iv2sls_1.se = sqrt(diag(sandwich::vcovCL(iv2sls_1, cluster = ~ccode,type = 'HC1'))) # Cluster Robust Standard Error


# IV 2SLS (2): Interactions between Economic Growth and Log Per Capital Income on Civil Conﬂict

## stage 1: 
t5_f1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L', "Y_0*GPCP_G", "Y_0*GPCP_G_L"))
## stage 2: 
t5_f2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G", "Y_0*GDP_G_L", "Y_0*GDP_G"),response = 'ANY_PRIO')

iv2sls_2 = ivreg(formula = t5_f1, instruments = t5_f2, data = master_df)
iv2sls_2.se = sqrt(diag(sandwich::vcovCL(iv2sls_2, cluster = ~ccode,type = 'HC1'))) # Cluster Robust Standard Error
rmse2 = sqrt(mean(iv2sls_2$residuals^2))

# IV 2SLS (3): Interactions between Economic Growth and ethnolinguistic fractionalization on Civil Conﬂict

## stage 1:
t5_f1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L', "ethfrac*GPCP_G", "ethfrac*GPCP_G_L"))
## stage 2: 
t5_f2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G", "ethfrac*GDP_G_L", "ethfrac*GDP_G"),response = 'ANY_PRIO')

iv2sls_3 = ivreg(formula = t5_f1, instruments = t5_f2, data = master_df)
iv2sls_3.se = sqrt(diag(sandwich::vcovCL(iv2sls_3, cluster = ~ccode,type = 'HC1')))
rmse3 = sqrt(mean(iv2sls_3$residuals^2))

# IV 2SLS (4): Interactions between Economic Growth and being an oil-exporting country on Civil Conﬂict

## stage 1:
t5_f1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L', "Oil*GPCP_G", "Oil*GPCP_G_L"))
## stage 2: 
t5_f2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G", "Oil*GDP_G_L", "Oil*GDP_G"),response = 'ANY_PRIO')

iv2sls_4 = ivreg(formula = t5_f1, instruments = t5_f2, data = master_df)
iv2sls_4.se = sqrt(diag(sandwich::vcovCL(iv2sls_4, cluster = ~ccode,type = 'HC1')))
rmse4 = sqrt(mean(iv2sls_4$residuals^2))


# IV 2SLS (5): Interactions between Economic Growth and being an mountainous country on Civil Conﬂict

## stage 1:
t5_f1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L', "lmtnest*GPCP_G", "lmtnest*GPCP_G_L"))
## stage 2: 
t5_f2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G", "lmtnest*GDP_G_L", "lmtnest*GDP_G"),response = 'ANY_PRIO')

iv2sls_5 = ivreg(formula = t5_f1, instruments = t5_f2, data = master_df)
iv2sls_5.se = sqrt(diag(sandwich::vcovCL(iv2sls_5, cluster = ~ccode,type = 'HC1')))
rmse5 = sqrt(mean(iv2sls_5$residuals^2))

stargazer(iv2sls_1,iv2sls_2,iv2sls_3,iv2sls_4,iv2sls_5,se = list(iv2sls_1.se, iv2sls_2.se, iv2sls_3.se, iv2sls_4.se, iv2sls_5.se), header = F, type = 'text', omit = c('Iccyear','Iccode'), omit.labels = c("Country-speciﬁc time trend","Country fixed effect"))

```


# T6: Economic shocks on the onset of civil conflict
```{r}
# IV 2SLS 1:
# stage 1:
m1formula1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'))
# stage 2: 
m1formula2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G"),response = 'ANY_PRIO_ON')

iv2sls_1 = ivreg(formula = m1formula2, instruments = m1formula1, data = master_df)
iv2sls_1.se = sqrt(diag(sandwich::vcovCL(iv2sls_1, cluster = ~ccode,type = 'HC1')))
rmse1 = sqrt(mean(iv2sls_1$residuals^2))

# IV 2SLS 2:
# stage 1:
m2formula1 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'))
# stage 2: 
m2formula2 = reformulate(c(grep('Iccyear|Iccode',x = names(master_df),value = T),'GDP_G_L', "GDP_G"),response = 'WAR_PRIO_ON')

iv2sls_2 = ivreg(formula = m2formula2, instruments = m2formula1, data = master_df)
iv2sls_2.se = sqrt(diag(sandwich::vcovCL(iv2sls_2, cluster = ~ccode,type = 'HC1')))
rmse2 = sqrt(mean(iv2sls_2$residuals^2))


stargazer(iv2sls_1,iv2sls_2,header = F, type = 'text', omit = c('Iccyear','Iccode'), omit.labels = c("Country-speciﬁc time trend","Country fixed effect"), se = list(iv2sls_1.se,iv2sls_2.se)) 
```


# Tc1
```{r}
tablec1 = merged_df[!is.na(merged_df$GDP_G),] %>% 
  group_by(Location) %>% 
  summarise(Year_count = length(year),
            Minor = sum(ANY_PRIO), 
            War = sum(WAR_PRIO)) %>% 
  arrange((Location)) %>% 
  janitor::adorn_totals()



tablec1 %>% knitr::kable(col.names = c('Country', 'Total Years', "Years of Civil Conﬂict ≥25 Deaths (PRIO/Uppsala)", "Years of Civil Conﬂict ≥1,000 Deaths (PRIO/Uppsala)"))
```
# T1
```{r}
master_df[!is.na(master_df$'GDP_G'),]  %>%
  summarise(mean = c(mean(ANY_PRIO, na.rm = T),
                     mean(ANY_PRIO_ON,na.rm = T),
                     mean(ANY_PRIO_OFF,na.rm = T),
                     mean(WAR_PRIO, na.rm = T),
                     mean(WAR_PRIO_ON,na.rm = T),
                     mean(WAR_PRIO_OFF,na.rm = T)),
           sd = c(sd(ANY_PRIO,na.rm = T),
                     sd(ANY_PRIO_ON,na.rm = T),
                     sd(ANY_PRIO_OFF,na.rm = T),
                     sd(WAR_PRIO,na.rm = T),
                     sd(WAR_PRIO_ON,na.rm = T),
                     sd(WAR_PRIO_OFF,na.rm = T)),
           obs = c(length(na.omit(ANY_PRIO)),
                    length(na.omit(ANY_PRIO_ON)),
                     length(na.omit(ANY_PRIO_OFF)),
                     length(na.omit(WAR_PRIO)),
                     length(na.omit(WAR_PRIO_ON)),
                     length(na.omit(WAR_PRIO_OFF)))
              ) %>% 
  add_column(.before = T, Label = c('ANY_PRIO', 'ANY_PRIO_ON','ANY_PRIO_OFF', 
               'WAR_PRIO', 'WAR_PRIO_ON', 'WAR_PRIO_OFF')) %>% 
  knitr::kable()
```

# Inversion Method

```{r} 

```



