---
title: "Replication of Miguel 2004 Civil Conflict and Economic Shock"
author: "Sam Tan"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    latex_engine: xelatex
    

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(tidyverse)
library(skimr)
knitr::opts_knit$set(root.dir = "/Users/samtan/Downloads/Replication of Miguel's study")
```

## Civil Conflict


```{r}
main =readxl::read_excel("ucdp-prio-acd-3-2005.xls")
#main =read_csv("ucdp-prio-acd-221.csv")
africa = read_csv('cow_code.csv')
# raw = haven::read_dta('dataverse_files-4/mss_repdata.dta')
```


```{r}
#main %>%  mutate(COW_location = as.numeric(COW_location)) %>% select(Startdate) %>% skimr::skim()

main %>% filter((YEAR >= 1981), (YEAR <= 1999), Location == 'Niger')



monadic = main %>% 
  select(Type, Intensity, YEAR, COW_location, Location) %>%
  pivot_wider(id_cols = c(YEAR,COW_location), names_from = Type,values_from = Intensity, values_fn = max, names_prefix = 'Type', values_fill = 0) 



monadic_africa_conflict = monadic %>% 
  filter(COW_location %in% africa$CCode) %>% 
  mutate(COW_location = as.numeric(COW_location))
  
monadic_africa_empty = map_df(1:nrow(africa), function(i){
  # For Namibia, only 9 years are observed (1990 - 1999), instead of all years. Source: Armed Conflict Dataset Codebook, Version 3-2005, page 24
  if (africa$StateNme[i] == 'Namibia') {
    bind_cols(Location = africa$StateNme[i], 
        COW_location = africa$CCode[i], 
        YEAR = 1990:1999)  # include 1980 and 2000 for the onset and offset variable
  }
  else{
    bind_cols(Location = africa$StateNme[i], 
        COW_location = africa$CCode[i], 
        YEAR = 1980:2000)
    }
})


monadic_africa_all = left_join(
  monadic_africa_empty, 
  monadic_africa_conflict, 
  by = c('COW_location','YEAR'))  %>% 
  mutate_if(is.numeric,coalesce,0) %>% # The default is peace. No conflict.
  mutate(WAR_PRIO = ((Type3 == 3)|(Type4 == 3)), 
         WAR_PRIO_ON = ((lag(WAR_PRIO == F, default = F) & (WAR_PRIO == T))),
         WAR_PRIO_OFF = ((lag(WAR_PRIO == T, default = F) & (WAR_PRIO == F))), 
         MINOR_PRIO = ((Type3 == 1)|(Type3 == 2)|(Type4 == 1) | (Type4 == 2)), 
         MINOR_PRIO_ON = ((lag(MINOR_PRIO == F, default = F) & (MINOR_PRIO == T))), 
         MINOR_PRIO_OFF = ((lag(MINOR_PRIO == T, default = F) & (MINOR_PRIO == F))), 
         ANY_PRIO = ((Type3 == 1)|(Type3 == 2)|(Type3 == 3)|(Type4 == 1) | (Type4 == 2) | (Type4 == 3)), 
         ANY_PRIO_ON = (lag(ANY_PRIO == F,default = F) & (ANY_PRIO == T)),
         ANY_PRIO_OFF = ((lag(ANY_PRIO == T, default = F) & (ANY_PRIO == F)))) 

monadic_africa_all$ANY_PRIO_ON[lag(monadic_africa_all$ANY_PRIO)] <- NA
monadic_africa_all$ANY_PRIO_OFF[!lag(monadic_africa_all$ANY_PRIO)] <- NA
monadic_africa_all$MINOR_PRIO_ON[lag(monadic_africa_all$MINOR_PRIO)] <- NA
monadic_africa_all$MINOR_PRIO_OFF[!lag(monadic_africa_all$MINOR_PRIO)] <- NA
monadic_africa_all$WAR_PRIO_ON[lag(monadic_africa_all$WAR_PRIO)] <- NA
monadic_africa_all$WAR_PRIO_OFF[!lag(monadic_africa_all$WAR_PRIO)] <- NA

monadic_africa_all =  monadic_africa_all %>%
    filter((YEAR >= 1981) & (YEAR <= 1999)) 

tablec1 = monadic_africa_all %>% 
  group_by(Location) %>% 
  summarise(Year_count = length(YEAR),
            Minor = sum(ANY_PRIO), 
            War = sum(WAR_PRIO)) %>% 
  arrange((Location)) %>% 
  janitor::adorn_totals()


tablec1 %>% knitr::kable(col.names = c('Country', 'Total
Years', "Years of Civil Conﬂict ≥25 Deaths (PRIO/Uppsala)",
"Years of Civil Conﬂict ≥1,000 Deaths (PRIO/Uppsala)"))

# TODO fix the on off set 
monadic_africa_all  %>% 
  summarise(mean = c(mean(ANY_PRIO, na.rm = T), 
                     mean(ANY_PRIO_ON,na.rm = T),
                     mean(ANY_PRIO_OFF,na.rm = T),
                     mean(WAR_PRIO, na.rm = T), 
                     mean(WAR_PRIO_ON,na.rm = T),
                     mean(WAR_PRIO_OFF,na.rm = T)),
           sd = c(sd(ANY_PRIO,na.rm = T), 
                     sd(ANY_PRIO_ON,na.rm = T),
                     sd(ANY_PRIO_OFF,na.rm = T), 
                     sd(WAR_PRIO,na.rm = T), 
                     sd(WAR_PRIO_ON,na.rm = T),
                     sd(WAR_PRIO_OFF,na.rm = T)), 
           obs = c(length(na.omit(ANY_PRIO)), 
                    length(na.omit(ANY_PRIO_ON)),
                     length(na.omit(ANY_PRIO_OFF)), 
                     length(na.omit(WAR_PRIO)), 
                     length(na.omit(WAR_PRIO_ON)),
                     length(na.omit(WAR_PRIO_OFF)))
              )
            
           
#cc =haven::read_dta("/Users/samtan/Downloads/Replication of Miguel's study/dataverse_files-4/mss_repdata.dta")

```

# Merge data

```{r}
df = read_csv('clean_data.csv')
merged_df = inner_join(x = df, y = monadic_africa_all,by = c('year' = 'YEAR', 'ccode' = 'COW_location'))

merged_df %>% select(year, country.x,ccode) %>% filter(ccode == 565 )

# write_csv(x = merged_df, file = 'merged_df.csv')
```

```{r}
library(fastDummies)
library(sandwich)
library(stargazer)


# model 1: Economic Growth Rate ~ Growth in rainfall at time t + Growth in rainfall at t - 1. 
m1 = lm(formula = GDP_G ~ GPCP_G + GPCP_G_L, data = merged_df)
m1.coef = m1$coefficients[c("GPCP_G","GPCP_G_L")]
m1.se = sqrt(diag(sandwich::vcovCL(m1, cluster = ~ccode,type = 'HC1')))

# model 2: Economic Growth Rate ~ Growth in rainfall, t +  Growth in rainfall, t - 1 + covariates
X = c('Y_0','polity2l','ethfrac','relfrac','Oil','lmtnest','lpopl1')

# fixed effect for each country (in dummies)
Iccode = fastDummies::dummy_cols(.data = merged_df$ccode,remove_selected_columns = T,remove_first_dummy = T) %>% tibble()

# extract the years for each country in dummies form
Iccyear = Iccode * merged_df$year 

# merge the dummies to the main dataframe
names(Iccode) = paste0("Iccode", names(Iccode))
names(Iccyear) = paste0("Iccyear", names(Iccyear))
Iccyear = Iccyear %>% rowid_to_column("ID")
Iccode = Iccode %>% rowid_to_column("ID")

dummies_df = left_join(x = Iccode, y = Iccyear, by = 'ID')

master_df = left_join(merged_df,dummies_df,by = c('...1' = 'ID'))  
# model formula for m2
m2formula = reformulate(termlabels = c(grep('Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L',X),response = 'GDP_G')

m2 = lm(formula = m2formula, data = master_df)
m2.coef = m2$coefficients[c('GPCP_G','GPCP_G_L',X)]
m2.se = sqrt(diag(sandwich::vcovCL(m2, cluster = ~ccode,type = 'HC1')))[c('GPCP_G','GPCP_G_L',X)]

# m3
m3formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L'),response = 'GDP_G')

m3 = lm(formula = m3formula, data = master_df)
m3.coef = m3$coefficients[c('GPCP_G','GPCP_G_L')]
m3.se = sqrt(diag(sandwich::vcovCL(m3, cluster = ~ccode,type = 'HC1')))[c('GPCP_G','GPCP_G_L')]

# m4
m4formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L',"GPCP_G_FL"),response = 'GDP_G')

m4 = lm(formula = m4formula, data = master_df)
m4.coef = m4$coefficients[c('GPCP_G','GPCP_G_L','GPCP_G_FL')]
m4.se = sqrt(diag(sandwich::vcovCL(m4, cluster = ~ccode,type = 'HC1')))[c('GPCP_G','GPCP_G_L','GPCP_G_FL')]


# m5
m5formula = reformulate(termlabels = c(grep('Iccode|Iccyear',x = names(master_df),value = T),'GPCP_G','GPCP_G_L','TOT_100_G'),response = 'GDP_G')

m5 = lm(formula = m5formula, data = master_df)
m5.coef = m5$coefficients[c('GPCP_G','GPCP_G_L','TOT_100_G')]
m5.se = sqrt(diag(sandwich::vcovCL(m5, cluster = ~ccode,type = 'HC1')))[c('GPCP_G','GPCP_G_L','TOT_100_G')]

# table 2
stargazer(m1,m2,m3,m4,m5,omit = c('Iccode', 'Iccyear'), omit.labels = c("Country fixed effect", "Country-speciﬁc time trend"),column.label = "Economic Growth Rate, t", covariate.labels = c("Growth in rainfall, t", "Growth in rainfall, t-1", "Growth in rainfall, t+1", "Growth in terms of trade t", "Log(GDP per capita), 1979", "Democracy (Polity
 IV), t-1","Ethnolinguistic fractionalization", "Religious fractionalization", "Oil-exporting Country", "Log(mountainous)", "Log(national popu-
 lation), t _ 1"))


```



